package net.fabricmc.example;

public enum villagerenchants {
    aqua_affinity,
    bane_of_arthropods,
    blast_protection,
    channeling,
    curse_of_binding,
    curse_of_vanishing,
    depth_strider,
    efficiency,
    feather_falling,
    fire_aspect,
    fire_protection,
    flame,
    fortune,
    frost_walker,
    impaling,
    infinity,
    knockback,
    looting,
    loyalty,
    luck_of_the_sea,
    lure,
    mending,
    multishot,
    piercing,
    power,
    projectile_protection,
    protection,
    punch,
    quick_charge,
    respiration,
    riptide,
    sharpness,
    silk_touch,
    smite,
    sweeping_edge,
    thorns,
    unbreaking,

    NONE
}
