name: build
run-name: ${{ github.actor }} is building the mod.
on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v3.13.0
        with:
          distribution: 'temurin'
          java-version: '20'
          cache: 'gradle'
      - run: ./gradlew build