name: build
run-name: ${{ github.actor }} is building the mod.
on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v3.13.0
        with:
          distribution: 'temurin'
          java-version: '20'
          cache: 'gradle'
      - name: Build
        run: chmod +x ./gradlew && ./gradlew build
      - uses: actions/upload-artifact@v3
        with:
          name: mod-jars
          path: ./build/libs/
          retention-days: 14