name: build-tag
run-name: ${{ github.actor }} is building the mod.
on:
  push:
    tags:
      - 'release-*'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v3.13.0
        with:
          distribution: 'temurin'
          java-version: '20'
          cache: 'gradle'
      - name: Build
        run: chmod +x ./gradlew && ./gradlew build
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: "build/libs/*"